### PR TITLE
Add section: Collaborating on large documents

### PR DESCRIPTION
**Pull request by nottrobin**
This is a new subsection under the "Submitting suggestions" heading suggested in #17.

There have been frustrations about the slow pace of making changes through pull requests, so this is a suggestion for how to ease that frustration.

I hope going forward we might evolve a few different patterns for collaboration that mix the technologies at our disposal. Although ultimately I think it is important to keep a rigorous formal process for approving the final version of any documents.

### CODE REVIEW

**Comment by nottrobin** [comment]
@anthonydillon do you have any other suggestions for how to make extensive changes or additions easier to do? Do you accept that, in the current model, getting, say, 30 new paragraphs approved is going to be a slow laborious process.

**Comment by anthonydillon** [comment]
I concede is my be slow but so is editing anything official. We should be
able to comment and propose changes quickly as a team.

**Comment by nottrobin** [comment]
@anthonydillon cool. I'm happy to shelve this, but we should hear more opinions first.

**Comment by anthonydillon** [comment]
Of course and this is just my opinion. It would be great to hear what
others think.

**Comment by anthonydillon** [comment]
Arm twisted :+1:

**Comment by deadlight** [comment]
I'll say that when it's easy to do so, we should use GitHub but we can use GDocs if we're collaborating or are finding editing via pull request too burdensome. :+1:

**Comment by WillMoggridge** [comment]
👍

**Pull request merged**
