### PR TITLE
Add ports for maas-ui

### PR DESCRIPTION
**Pull request by huwshimi**
Multiple ports are required by the maas-ui project.

### CODE REVIEW

**Comment by jpmartinspt** [comment]
@huwshimi @squidsoup Do we need to open all these ports in the container for the UI to be usable?

**Comment by huwshimi** [comment]
@jpmartinspt only one port is exposed, the other two are proxied to inside the container, but we can expose those individually as needed.

**Comment by jpmartinspt** [comment]
@huwshimi So basically you might need to exposed them for dev purposes? If that's the case fix the linting and merge ahead!

**Comment by huwshimi** [comment]
@jpmartinspt Yep that's right! Sometimes we'll need to run one of the servers in isolation.

**Review by jpmartinspt — APPROVED** [review]

**Comment by huwshimi** [comment]
Thanks @jpmartinspt!

**Pull request merged**
