### PR TITLE
CONTRIBUTING.md: Rules for approving pull requests

### PR DESCRIPTION
**Pull request by nottrobin**
Define the threshold for and practice around approving a pull request.

### CODE REVIEW

**Comment by nottrobin** [comment]
@anthonydillon said:

> I don't think we need to move too quickly on these reviews. I would like to say at least 2 +1's and have the PR up for more than 24 hours so everyone gets a chance to review.

**Comment by nottrobin** [comment]
@deadlight rebutted:

> @anthonydillon I think that it would be better to get them closed relatively quickly and have any changes issued as PRs. Especially useful for times like right now where I have more changes waiting on a PR approval.

**Comment by nottrobin** [comment]
I like @anthonydillon's idea. I think we should be slow about making policy. Once something is merged, it's official. It can be pointed to in arguments to shut them down. It is The Way We Work from then on.

**Comment by WillMoggridge** [comment]
Going forward, I definitely prefer that it is left for 24 hours. As it stands right now, while we flesh out the repository a bit, I don't mind so much.

**Comment by nottrobin** [comment]
@anthonydillon said:

> But we will miss people opinions and once it lands becomes approved and may be difficult to change with another PR.

**Comment by nottrobin** [comment]
I've updated the wording to include @anthonydillon's suggestion (not yet agreed)

**Comment by anthonydillon** [comment]
Agree @WillMoggridge

**Comment by anthonydillon** [comment]
But we need to transition from fast to slow and I'm not sure how and who makes that call. It also devalued the current content because we are in our "fast phase"

**Comment by deadlight** [comment]
Agreed but the current content is binding even if we are moving fast. It can't be devalued, just slowly changed.

**Comment by nottrobin** [comment]
Yes I think that is a very real danger @anthonydillon. I'm not sure we should really have a fast phase.

**Comment by deadlight** [comment]
We need some exceptions: for instance, in my HTML doc work I want the PR for creating the file to be landed before I put another in for adding something else about templates. I don't think waiting 24hrs wait will do anything there other than discouraging authors from bothering.

**Comment by nottrobin** [comment]
I think the main problem is, as @deadlight said, that we need to be able to do work building on an existing document, which may not exist yet.

In which case we could define a process for creating new documents whereby there's always a PR to create the doc simply with a title and nothing else, like this: https://github.com/ubuntudesign/webteam-practices/pull/10. These could then have different rules - can be approved and merged immediately by a single team-member.

That would mean we can then continue to work on submitting things into that new document, regardless of what other work is coming in. Each heading in that document can be considered separately.

**Comment by deadlight** [comment]
Good point @nottrobin, that would simplify matters. In this one-off instance, can I consider #11 cleared for merging?

**Comment by nottrobin** [comment]
@deadlight I think so. @anthonydillon, @WillMoggridge ?

**Comment by anthonydillon** [comment]
I am happy with the concept of genesis (fast) reviews and structural and amendments being (slow)

**Comment by WillMoggridge** [comment]
Yeah, all good

**Comment by Lukewh** [comment]
It's probably still good to have at least 1 review of a PR even for pages with a title to have some kind of checkpoint. Just my 2c.

**Comment by anthonydillon** [comment]
@Lukewh agree, all PRs into this repo should have 2 +1's but "slow" PRs need to be left for 24 hours so everyone catches it.

**Comment by Lukewh** [comment]
@anthonydillon 👍

**Comment by nottrobin** [comment]
Agreed @Lukewh, @anthonydillon. I'll codify that in a new PR soon.

**Comment by anthonydillon** [comment]
@nottrobin could you land or close this one down please.

**Pull request merged**
